# Generated by Django 4.1.2 on 2022-11-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='first',
            field=models.CharField(default='jashan', max_length=64),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last',
            field=models.CharField(default='deep', max_length=64),
        ),
    ]
